# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id$
Configuration parameters:
  url = http://ja.kinpri-rush-live.wikia.com/
  name = kinpriRushLive

Please do not commit this to the Git repository!
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'kinpriRushLive'
        self.langs = {
            'ja': 'ja.kinpri-rush-live.wikia.com',
        }

    def scriptpath(self, code):
        return {
            'ja': '',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'ja': u'1.19.24',
        }[code]

    def protocol(self, code):
        return {
            'ja': u'http',
        }[code]
